"""allow null field users

Revision ID: 49f45fb6d0d4
Revises: bb93600010b6
Create Date: 2018-01-30 00:17:14.147949

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '49f45fb6d0d4'
down_revision = 'bb93600010b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'full_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
